# Generated by Django 3.0.6 on 2020-05-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='user_id',
        ),
    ]
